### ISSUE TITLE
Timeout waiting for connection from pool after uploading/putting 10 files successfully

### ISSUE THREAD

**Issue by anohl9** [lahsivjar/gcp-storage-wagon#19] opened 2019-01-03 07:28 UTC
It seems like there is a leak in the pool that maintains connections towards Google Cloud Storage. After successfully uploading/putting 10 files, the process hangs for a number of minutes, until the below stacktrace is printed:
`[WARNING] Failed to upload checksum IOPG/IOPG-swagger-jaxrs/maven-metadata.xml.md5: Failed to transfer wagon-74871373d82f459ca54746808aa2c89c4789050654382797971.tmp to IOPG/IOPG-swagger-jaxrs/maven-metadata.xml.md5
org.apache.maven.wagon.TransferFailedException: Failed to transfer wagon-74871373d82f459ca54746808aa2c89c4789050654382797971.tmp to IOPG/IOPG-swagger-jaxrs/maven-metadata.xml.md5
    at com.lahsivjar.GcpStorageWagon.put (GcpStorageWagon.java:153)
    at org.eclipse.aether.transport.wagon.WagonTransporter$PutTaskRunner.run (WagonTransporter.java:686)
    at org.eclipse.aether.transport.wagon.WagonTransporter.execute (WagonTransporter.java:435)
    at org.eclipse.aether.transport.wagon.WagonTransporter.put (WagonTransporter.java:418)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.uploadChecksum (BasicRepositoryConnector.java:557)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.uploadChecksums (BasicRepositoryConnector.java:532)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask (BasicRepositoryConnector.java:513)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:360)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put (BasicRepositoryConnector.java:298)
    at org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:320)
    at org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:223)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy (DefaultRepositorySystem.java:384)
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy (DefaultArtifactDeployer.java:139)
    at org.apache.maven.plugin.deploy.AbstractDeployMojo.deploy (AbstractDeployMojo.java:167)
    at org.apache.maven.plugin.deploy.DeployMojo.execute (DeployMojo.java:157)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: com.google.cloud.storage.StorageException: Timeout waiting for connection from pool
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate (HttpStorageRpc.java:220)
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.open (HttpStorageRpc.java:758)
    at com.google.cloud.storage.BlobWriteChannel$2.call (BlobWriteChannel.java:69)
    at com.google.cloud.storage.BlobWriteChannel$2.call (BlobWriteChannel.java:66)
    at com.google.api.gax.retrying.DirectRetryingExecutor.submit (DirectRetryingExecutor.java:89)
    at com.google.cloud.RetryHelper.run (RetryHelper.java:74)
    at com.google.cloud.RetryHelper.runWithRetries (RetryHelper.java:51)
    at com.google.cloud.storage.BlobWriteChannel.open (BlobWriteChannel.java:66)
    at com.google.cloud.storage.BlobWriteChannel.<init> (BlobWriteChannel.java:37)
    at com.google.cloud.storage.StorageImpl.writer (StorageImpl.java:497)
    at com.google.cloud.storage.StorageImpl.writer (StorageImpl.java:492)
    at com.google.cloud.storage.StorageImpl.writer (StorageImpl.java:81)
    at com.lahsivjar.GcpStorageWagon.put (GcpStorageWagon.java:138)
    at org.eclipse.aether.transport.wagon.WagonTransporter$PutTaskRunner.run (WagonTransporter.java:686)
    at org.eclipse.aether.transport.wagon.WagonTransporter.execute (WagonTransporter.java:435)
    at org.eclipse.aether.transport.wagon.WagonTransporter.put (WagonTransporter.java:418)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.uploadChecksum (BasicRepositoryConnector.java:557)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.uploadChecksums (BasicRepositoryConnector.java:532)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask (BasicRepositoryConnector.java:513)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:360)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put (BasicRepositoryConnector.java:298)
    at org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:320)
    at org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:223)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy (DefaultRepositorySystem.java:384)
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy (DefaultArtifactDeployer.java:139)
    at org.apache.maven.plugin.deploy.AbstractDeployMojo.deploy (AbstractDeployMojo.java:167)
    at org.apache.maven.plugin.deploy.DeployMojo.execute (DeployMojo.java:157)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
    at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking (ConnPoolByRoute.java:414)
    at org.apache.http.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry (ConnPoolByRoute.java:300)
    at org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection (ThreadSafeClientConnManager.java:243)
    at org.apache.http.impl.client.DefaultRequestDirector.execute (DefaultRequestDirector.java:422)
    at org.apache.http.impl.client.AbstractHttpClient.doExecute (AbstractHttpClient.java:835)
    at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:83)
    at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:108)
    at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:56)
    at com.google.api.client.http.apache.ApacheHttpRequest.execute (ApacheHttpRequest.java:65)
    at com.google.api.client.http.HttpRequest.execute (HttpRequest.java:981)
    at com.google.cloud.storage.spi.v1.HttpStorageRpc.open (HttpStorageRpc.java:748)
    at com.google.cloud.storage.BlobWriteChannel$2.call (BlobWriteChannel.java:69)
    at com.google.cloud.storage.BlobWriteChannel$2.call (BlobWriteChannel.java:66)
    at com.google.api.gax.retrying.DirectRetryingExecutor.submit (DirectRetryingExecutor.java:89)
    at com.google.cloud.RetryHelper.run (RetryHelper.java:74)
    at com.google.cloud.RetryHelper.runWithRetries (RetryHelper.java:51)
    at com.google.cloud.storage.BlobWriteChannel.open (BlobWriteChannel.java:66)
    at com.google.cloud.storage.BlobWriteChannel.<init> (BlobWriteChannel.java:37)
    at com.google.cloud.storage.StorageImpl.writer (StorageImpl.java:497)
    at com.google.cloud.storage.StorageImpl.writer (StorageImpl.java:492)
    at com.google.cloud.storage.StorageImpl.writer (StorageImpl.java:81)
    at com.lahsivjar.GcpStorageWagon.put (GcpStorageWagon.java:138)
    at org.eclipse.aether.transport.wagon.WagonTransporter$PutTaskRunner.run (WagonTransporter.java:686)
    at org.eclipse.aether.transport.wagon.WagonTransporter.execute (WagonTransporter.java:435)
    at org.eclipse.aether.transport.wagon.WagonTransporter.put (WagonTransporter.java:418)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.uploadChecksum (BasicRepositoryConnector.java:557)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.uploadChecksums (BasicRepositoryConnector.java:532)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$PutTaskRunner.runTask (BasicRepositoryConnector.java:513)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:360)
    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.put (BasicRepositoryConnector.java:298)
    at org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:320)
    at org.eclipse.aether.internal.impl.DefaultDeployer.deploy (DefaultDeployer.java:223)
    at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy (DefaultRepositorySystem.java:384)
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy (DefaultArtifactDeployer.java:139)
    at org.apache.maven.plugin.deploy.AbstractDeployMojo.deploy (AbstractDeployMojo.java:167)
    at org.apache.maven.plugin.deploy.DeployMojo.execute (DeployMojo.java:157)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)`

**Comment by lahsivjar** [comment] 2019-01-15 04:08
@anohl9 Sorry, I am not able to generate this on my local. Is it possible for you to construct a simple test case for reproduction?

**Comment by lahsivjar** [comment] 2019-01-29 09:47
@anohl9 Any updates?

**Comment by dgvigil** [comment] 2019-01-30 22:08
I was trying this out today for the first time and noticed that some repo's builds would timeout after pushing files as well. Unfortunately, I'm working on a private company repo that I can't share and replicate for you.

**Comment by lahsivjar** [comment] 2019-01-31 08:43
@dgvigil I wrote a test case in an effort to reproduce the problem with the wagon but it works without any issue(https://github.com/lahsivjar/gcp-storage-wagon/pull/22/commits/afd582df6a18e6a1afd2cb062ad8bd23b518b91c)

Can you give me some generic information like the number of dependencies and the stage of failure wrt the full build?

**Comment by lahsivjar** [comment] 2019-01-31 10:03
Hmm, the cause seems to be the underlying thread pool:

```Caused by: com.google.cloud.storage.StorageException: Timeout waiting for connection from pool
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.open(HttpStorageRpc.java:758)
	at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:492)
	at com.google.cloud.storage.StorageImpl.writer(StorageImpl.java:81)
	at com.lahsivjar.GcpStorageWagon.put(GcpStorageWagon.java:150)
	... 36 more
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute.getEntryBlocking(ConnPoolByRoute.java:414)
	at org.apache.http.impl.conn.tsccm.ConnPoolByRoute$1.getPoolEntry(ConnPoolByRoute.java:300)
org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager$1.getConnection(ThreadSafeClientConnManager.java:243)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:422)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
```

**Comment by dgvigil** [comment] 2019-01-31 15:08
My issue is happening during a `mvn deploy` in Google Cloud Build.

``` 
Step #2 - "DEPLOY ARTIFACT": [INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ project1 ---
Step #2 - "DEPLOY ARTIFACT": Downloading: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/1.5.6/plexus-utils-1.5.6.jar (251 kB at 7.0 MB/s)
Step #2 - "DEPLOY ARTIFACT": Downloading: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/0.1.0-SNAPSHOT/maven-metadata.xml
Downloaded: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/0.1.0-SNAPSHOT/maven-metadata.xml (793 B at 1.3 kB/s)
Step #2 - "DEPLOY ARTIFACT": Uploading: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/0.1.0-SNAPSHOT/project1-0.1.0-20190131.150057-4.jar
Uploaded: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/0.1.0-SNAPSHOT/project1-0.1.0-20190131.150057-4.jar (226 kB at 176 kB/s)
Step #2 - "DEPLOY ARTIFACT": Uploading: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/0.1.0-SNAPSHOT/project1-0.1.0-20190131.150057-4.pom
Uploaded: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/0.1.0-SNAPSHOT/project1-0.1.0-20190131.150057-4.pom (4.9 kB at 4.0 kB/s)
Step #2 - "DEPLOY ARTIFACT": Downloading: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/maven-metadata.xml
[WARNING] Checksum validation failed, expected 3bd33fca28b729eb9f54f8bf29709fe3b2b4fd09 but is 7de964a2431442478ff93d5ba56be1f5a0e4ba2f for gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/maven-metadata.xml
[WARNING] Could not validate integrity of download from gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/maven-metadata.xml: Checksum validation failed, expected 3bd33fca28b729eb9f54f8bf29709fe3b2b4fd09 but is 7de964a2431442478ff93d5ba56be1f5a0e4ba2f
[WARNING] Checksum validation failed, expected 3bd33fca28b729eb9f54f8bf29709fe3b2b4fd09 but is 7de964a2431442478ff93d5ba56be1f5a0e4ba2f for gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/maven-metadata.xml
Step #2 - "DEPLOY ARTIFACT": Downloaded: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/maven-metadata.xml (303 B at 367 B/s)
Step #2 - "DEPLOY ARTIFACT": Uploading: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/0.1.0-SNAPSHOT/maven-metadata.xml
Uploaded: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/0.1.0-SNAPSHOT/maven-metadata.xml (793 B at 602 B/s)
Step #2 - "DEPLOY ARTIFACT": Uploading: gs://project1-999999#project1-mavenrepository/snapshot/com/company1/project1/project1/maven-metadata.xml 
```

This is when it hangs and till it finally times out. The project and company have been redacted. 
BTW: Thank you for your work on this project.

**Comment by lahsivjar** [comment] 2019-03-11 18:55
Should be fixed in PR: https://github.com/lahsivjar/gcp-storage-wagon/pull/23 and released in version `2.1`

**Closed by lahsivjar** 2019-03-11 18:55 UTC
Labels: investigate
